In [24]:
import numpy as np
import scipy

# 1

In [2]:
a = np.array([[1,2,3], [4,0,6], [7,8,9]])
b = np.array([12,2,1])
np.linalg.solve(a,b)

array([-9.2       ,  0.9       ,  6.46666667])

# 2

In [15]:
a = np.array([[1,2,-1],[3,-4,0],[8,-5,3],[2,0,-5],[11,4,-7]])
b = np.array([1,7,12,7,15])
np.linalg.lstsq(a,b)

/home/alex/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.19707162, -0.92226835, -0.83201776]),
 array([1.1288856]),
 3,
 array([15.11918528, 10.05849193,  3.77319183]))

# 3

In [10]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[12,2,1]])
np.linalg.det(a)

-9.51619735392994e-16

система не имеет единого решения, так как ранг расширенной матрицы больше ранга оригинальной матрицы

In [13]:
c = np.concatenate((a, b.T), axis=1)
c

array([[ 1,  2,  3, 12],
       [ 4,  5,  6,  2],
       [ 7,  8,  9,  1]])

In [14]:
np.linalg.matrix_rank(a), np.linalg.matrix_rank(c)

(2, 3)

# 4

In [25]:
a = np.array([[1,2,3],[2,16,21],[4,28,73]])
p,l,u = scipy.linalg.lu(a)
p,l,u

AttributeError: module 'scipy' has no attribute 'linalg'